apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reactjs-frontend.name" . }}
  labels:
    app: {{ include "reactjs-frontend.name" . }}
spec:
  replicas: {{ .Values.autoscaling.minReplicas }}
  selector:
    matchLabels:
      app: {{ include "reactjs-frontend.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "reactjs-frontend.name" . }}
    spec:
      containers:
        - name: react-frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi

