apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reactjs-frontend-ingress
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"  
    alb.ingress.kubernetes.io/target-type: "ip"  
    alb.ingress.kubernetes.io/success-code: "200"  
spec:
  rules:
  - host: reactjs.cloudraja.freeddns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: reactjs-frontend-service
            port:
              number: 80
