apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reactjs-frontend-ingress
spec:
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: reactjs-frontend
                port:
                  number: 80

