# react-helm-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: react-app
