apiVersion: v1
kind: Service
metadata:
  name: {{ include "reactjs-frontend.name" . }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "reactjs-frontend.name" . }}
  type: LoadBalancer

